[tool.poetry]
name = "serverless-framework"
version = "0.1.0"
description = ""
authors = ["hosana <hosana.pires@provafacilnaweb.com.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
